all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: 44.247.114.198
        server-two:
          ansible_host: 16.148.26.150

  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/aws
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
